VERT="\\033[1;32m"
NORM="\\033[0;39m"
ROUGE="\\033[1;31m"
BLEU="\\033[1;34m"
BLANC="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"

pre_install () {
    /bin/true
}

post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	update-desktop-database -q
	update-mime-database usr/share/mime &> /dev/null
	mkdir -pv /var/log/VisualSFM
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
